### ISSUE TITLE
I get this error: NSCocoaErrorDomain.3587 when running Cake

### ISSUE THREAD

**Issue by abbasmousavi** [mxcl/Cake#49]
I get this error when running Cake

<img width="488" alt="screenshot 2019-03-06 at 11 54 45" src="https://user-images.githubusercontent.com/1249875/53879561-bf997f00-4006-11e9-9f0d-1e6d728c5f16.png">

**Comment by gcox** [comment]
@abbasmousavi I've seen that too. 

First, I believe you need to make sure the command line tools are set to the Xcode 10.2+ tools

* Try cleaning the build
* Use the convenient "rm -rf 'Derived Data'" menu item in Cake
* Restart Xcode

Some combination of those 3 bullets has worked for me when I run into it.

**Comment by abbasmousavi** [comment]
Thanks @gcox, It worked with a random combination of your instructions!
But after the first installation on the simulator, I get this error every time trying to run the app on the simulator.

<img width="419" alt="screenshot 2019-03-06 at 12 27 23" src="https://user-images.githubusercontent.com/1249875/53881392-7c8dda80-400b-11e9-8b17-500b24d88151.png">

**Comment by gcox** [comment]
@abbasmousavi Unfortunately, I have not seen that one. The screenshot is clipped, is it the .app package that the error mentions or something else? Regardless, I'd try any/all of the following to see if that issue continues:

* Clean the build, try again
* Restart the simulator, try again
* Delete the app, try again

**Comment by abbasmousavi** [comment]
@gcox The problem is, every time I clean the app from simulator It installs and runs fine for the first time, but next time (without cleaning the app) it shows this error.

**Comment by gcox** [comment]
@abbasmousavi I'm actually seeing it now too. Haven't gotten around it yet.

**Comment by abbasmousavi** [comment]
@gcox It seems that it only happens with the projects generated with cake itself. I have made a new project with xcode, then integrated the cake, and it has not this problem.

**Comment by mxcl** [comment]
Figured out the template bug I think.

**Comment by gcox** [comment]
I'm still seeing the same 'Could not hardlink copy' error. Was one of your earlier commits supposed to fix it or were you just saying you figured out the cause?

**Comment by mxcl** [comment]
I have yet to commit the fix.

**Comment by mxcl** [comment]
Making a release.
