### ISSUE TITLE
"Update Dependencies" menu item always generates this error

### ISSUE THREAD

**Issue by abbasmousavi** [mxcl/Cake#54]
"Update Dependencies" menu item always generates this error

<img width="532" alt="Screen Shot 2019-03-10 at 2 25 10 PM" src="https://user-images.githubusercontent.com/1249875/54086512-01496300-4342-11e9-8a10-e955dbb2b5b5.png">

**Comment by mxcl** [comment]
Cannot reproduce, you’re going to have to give me more breadcrumbs.

**Comment by gcox** [comment]
I've seen this too, its another one of those "you probably need to clean, delete DerivedData, restart Xcode" deals. I haven't reproduced it while debugging the Cake project though.

**Comment by mxcl** [comment]
It’s odd (and irritating that) the alert doesn’t contain more information. I imagine the Console.app would have some more logs though.

**Comment by mxcl** [comment]
K, it does this when no dependencies are specified. Can fix.

**Comment by abbasmousavi** [comment]
In the `CakeProject.swift` method `public func updateDependencies() throws` tries to run

```
/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift package --build-path swift-pm update
```
in `.cake` directory and it gets 

```
error: root manifest not found
```
